### ISSUE TITLE
Hierarchical deletion

### ISSUE THREAD

**Issue by leroydev** [overlookmotel/sequelize-hierarchy#48] opened 2016-03-07 19:02 UTC
Consider the following, fictional hierarchy, made with this library:
```
1
   1.1
         1.1.1
```
So `1.1.1` is a child of `1.1`, which is a child of `1`.

Would it be possible to start at either one of those three and delete all the children, recursively, with  this library? Or could you point me towards a code example which can do this? I can't seem to find any documentation, issues or code related to this.

**Comment by leroydev** [comment] 2016-03-07 22:30
Well, I implemented this myself, but it's not the most efficient nor cleanest solution, how I do it at the moment, per unit I want to delete:

1 - Delete ancestor references:
```
sequelize.models.Unitancestor.destroy({
      where: {
        UnitId: UnitIdToDelete
      }
})
```
2 - Remove children references:
```
models.Unit.update({parentId: null}, {
      where: {
        parentId: UnitIdToDelete
      },
})
```
3 - Remove the unit itself:
```
models.Unit.destroy({
      where: {
        id: unitId
      },
})
```
I think it has to be done this way because of the foreign key constraints that get generated by `Unit.isHierarchy();`.

**Comment by overlookmotel** [comment] 2016-03-28 20:53
Hi @leroydev.

Sorry I've been very slow to reply on this.

To clarify: are you trying to delete all the children of '1', or all the ancestors of '1.1.1'?

**Comment by overlookmotel** [comment] 2016-03-28 20:56
You should be able to delete any item without directly accessing the Unitancestor table.

But you have to delete them in top-down order i.e. delete '1.1.1' first, then '1.1', then '1'.

If you try to do it in the opposite order, you'll be trying to delete a Unit which has children still attached, which is illegal.

Please let me know your thoughts.

**Comment by leroydev** [comment] 2016-03-30 08:31
Ah true.. Thanks, I didn't think of doing it that way yet. So this is how I do it at the moment, for people interested:

1. I fetch the model I want to delete fully (so I also want to delete it's children)
2. I call `model.getDescendents()`
3. I sort the result of `model.getDescendents()` descending on 'hierarchyLevel' so the models without children get deleted first. I do this with `descendents = _.sortBy(descendents, 'hierarchyLevel').reverse();` (note: with the help of lodash)
4. I iterate through this sorted list and call `destroy()` on the model instances.
5. I call `destroy()` on the root model.

**Comment by overlookmotel** [comment] 2016-03-30 14:22
@leroydev I can only see one optimization to your method. You can do the sorting within the Sequelize call rather than using `lodash` to sort as a separate step.

```js
model.getDescendents( { order: [ [ 'hierarchyLevel', 'DESC'] ] } )
```

Then you can remove step (3). Complete code could be:

```js
function deleteWithChildren(node) {
    return node.getDescendents( { order: [ [ 'hierarchyLevel', 'DESC'] ] } )
    .each(function(child) {
        return child.destroy();
    })
    .then(function() {
        return node.destroy();
    });
}
```

I haven't tested this, but it should work. Would you mind letting me know if it does?

I also wonder if this could be done automatically in the database (i.e. delete a node and it also deletes all descendents) by setting `onDelete: 'CASCADE'` in the hierarchy options. But, again, I've not tested this.

**Comment by leroydev** [comment] 2016-03-30 21:23
@overlookmotel Ah, true, that's cleaner. Yes, your code works. :)

You mean setting `onDelete: 'CASCADE'` in the model definition right? How would I do that? By writing the associations out myself instead of just calling `model.isHierarchy();`?

**Comment by overlookmotel** [comment] 2016-03-31 12:43
I mean by including it in the hierarchy options when you define the table.

You can do that by calling `.isHierarchy( { onDelete: 'CASCADE' } )` or in the model definition:

```js
var folder = sequelize.define(
    'folder',
    { name: Sequelize.STRING },
    { hierarchy: { onDelete: 'CASCADE' } }
);
```

I just realised this option isn't documented. But I'm also not sure if it works!

Want to give it a go?

**Comment by leroydev** [comment] 2016-03-31 14:35
Calling `isHierarchy({onDelete: 'CASCADE'})` works and deletes all child nodes as expected. Setting it in the model definition like that doesn't work, I get an error when the schema gets synced:

```
 C:\taw3\node_modules\sequelize\lib\associations\has-many.js:34
    throw new Error('N:M associations are not supported with hasMany. Use belong
sToMany instead');
    ^

Error: N:M associations are not supported with hasMany. Use belongsToMany instea
d
    at new HasMany (C:\taw3\node_modules\sequelize\lib\associations\has-many.js:
34:11)
    at Mixin.hasMany (C:\taw3\node_modules\sequelize\lib\associations\mixin.js:1
81:21)
    at isHierarchy (C:\taw3\node_modules\sequelize-hierarchy\lib\modelExtends.js
:71:9)
    at module.exports.afterDefine (C:\taw3\node_modules\sequelize-hierarchy\lib\
hooksUniversal.js:46:24)
    at C:\taw3\node_modules\sequelize\lib\hooks.js:122:21
    at Array.forEach (native)
    at Hooks.runHooks (C:\taw3\node_modules\sequelize\lib\hooks.js:120:13)
    at Sequelize.define (C:\taw3\node_modules\sequelize\lib\sequelize.js:603:8)
    at new BelongsToMany (C:\taw3\node_modules\sequelize\lib\associations\belong
s-to-many.js:161:43)
    at Mixin.belongsToMany (C:\taw3\node_modules\sequelize\lib\associations\mixi
n.js:260:21)
    at sequelize.define.classMethods.associate (C:\taw3\server\api\unit\unit.mod
el.js:40:14)
    at C:\taw3\server\api\models\index.js:27:19
    at Array.forEach (native)
    at Object.<anonymous> (C:\taw3\server\api\models\index.js:25:2)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\taw3\server\config\seed.js:9:17)
```

Also, how would I only cascade delete for certain `destroy` calls when I set `onDelete: 'CASCASDE'`? Or is that just not possible and should I use the previous method if that's my requirement?

**Comment by overlookmotel** [comment] 2016-04-08 12:28
@leroydev I'll check out that error when I get a chance.

Setting `onDelete: 'CASCADE'` is a table-level setting. It's the database itself that provides the cascading deletes, so it's not possible to only cascade deletes for certain calls. As you say, if you want to do that, you need to delete all children in order yourself.

**Comment by overlookmotel** [comment] 2016-06-14 23:49
@leroydev Rather belatedly, I've check on the error your found. With `sequelize` v3.23.3 and `sequelize-hierarchy` v0.5.8 I can't reproduce it.

Closing this issue, but if you find an error still exists, please feel free to re-open it or post another comment.

**Closed by overlookmotel** 2016-06-14 23:49 UTC

**Comment by deksden** [comment] 2017-08-04 10:01
Found this via search, but i m sure info about deleting nodes should be specified in readme! 

```
isHierarchy({onDelete: 'CASCADE'}) 
```

Do you need some PR on readme?

**Comment by leroydev** [comment] 2017-08-04 11:48
@deksden Would be good to have in the readme in my opinion. I'd support such a PR. 👍

**Comment by deksden** [comment] 2017-08-04 13:48
Here it is: https://github.com/overlookmotel/sequelize-hierarchy/pull/131
