### ISSUE TITLE
findAll() does not return simple nested JSON

### ISSUE THREAD

**Issue by aaronovz1** [overlookmotel/sequelize-hierarchy#133] opened 2017-08-04 21:52 UTC
Maybe I'm doing something wrong or perhaps something broke in recent version of Sequelize. When I run findAll({hiararchy: true}) I don't get a simple JSON output like what is shown in the example on the front page. I even tried using the attributes keyword to select 3 columns but it still has all the Sequelize meta data. If I use "raw:true" then I get a simple JSON object but there is no nesting.

Model/index.js (from sequelize express example)
```javascript
"use strict";

var fs        = require("fs");
var path      = require("path");
var Sequelize = require("sequelize");
var env       = process.env.NODE_ENV || "development";
var config    = require(path.join(__dirname, '..', 'config', 'config.json'))[env];
var sequelize = new Sequelize(config.database, config.username, config.password, config);
var db        = {};

fs
  .readdirSync(__dirname)
  .filter(function(file) {
    return (file.indexOf(".") !== 0) && (file !== "index.js");
  })
  .forEach(function(file) {
    var model = sequelize.import(path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(function(modelName) {
  if ("associate" in db[modelName]) {
    db[modelName].associate(db);
  }
});


db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```
Model
```javascript
"use strict";

var SequelizeH = require('sequelize-hierarchy')();

module.exports = function(sequelize, Sequelize) {

  var Category = sequelize.define('Category', {
    name: {
      type:Sequelize.STRING,
      allowNull: false
    }
  }, {underscored: true});

  Category.isHierarchy();

  return Category;
}
```

findAll
```javascript
var models = require("../models");
models.Category.findAll({
    hierarchy: true,
    attributes: ['id','parent_id', 'name']
  }).then(function(results) {
    console.log(results)
    res.render('index', { nested_cat: results });
  });
```

**Comment by overlookmotel** [comment] 2017-08-09 09:53
Hi @aaronovz1.

Sorry, some confusion here. The intended behaviour is to return Sequelize model instances, same as `.findAll()` does without the `hierarchy` option. The example in the README shows plain JS objects returned just to make the example readable.

And `hierarchy` option is not compatible with `raw` option.

To do what you're trying to do, I'd suggest fetching the results with `.findAll()` and then turning them into plain JS objects afterwards. You could use [sequelize-values](https://www.npmjs.com/package/sequelize-values) plugin for this, for example.

Am closing this issue as I think this answers it. Feel free to re-open if you have further questions.

**Comment by aaronovz1** [comment] 2017-08-09 20:52
I am not using the raw option and I still get a flat list of model instances when passing "hierarchy: true". So basically I am getting the results as if I am just calling .findAll(). What I would expect is output like in the README where each parent has an array of children. The result I see for .findAll() and .findAll({hierarchy: true}) is the SAME.

```
[ Category {
    dataValues: { id: 1, parent_id: null, name: 'C1.0' },
    _previousDataValues: { id: 1, parent_id: null, name: 'C1.0' },
    _changed: {},
    _modelOptions: 
     { timestamps: true,
       validate: {},
       freezeTableName: false,
       underscored: true,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: [Object],
       indexes: [],
       name: [Object],
       omitNull: false,
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    _options: 
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       raw: true,
       attributes: [Array] },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false },
  Category {
    dataValues: { id: 2, parent_id: null, name: 'C2.0' },
    _previousDataValues: { id: 2, parent_id: null, name: 'C2.0' },
    _changed: {},
    _modelOptions: 
     { timestamps: true,
       validate: {},
       freezeTableName: false,
       underscored: true,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: [Object],
       indexes: [],
       name: [Object],
       omitNull: false,
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    _options: 
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       raw: true,
       attributes: [Array] },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false },
  Category {
    dataValues: { id: 3, parent_id: null, name: 'C3.0' },
    _previousDataValues: { id: 3, parent_id: null, name: 'C3.0' },
    _changed: {},
    _modelOptions: 
     { timestamps: true,
       validate: {},
       freezeTableName: false,
       underscored: true,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: [Object],
       indexes: [],
       name: [Object],
       omitNull: false,
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    _options: 
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       raw: true,
       attributes: [Array] },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false },
  Category {
    dataValues: { id: 4, parent_id: 1, name: 'C1.1' },
    _previousDataValues: { id: 4, parent_id: 1, name: 'C1.1' },
    _changed: {},
    _modelOptions: 
     { timestamps: true,
       validate: {},
       freezeTableName: false,
       underscored: true,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: [Object],
       indexes: [],
       name: [Object],
       omitNull: false,
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    _options: 
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       raw: true,
       attributes: [Array] },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false },
  Category {
    dataValues: { id: 5, parent_id: 2, name: 'C2.1' },
    _previousDataValues: { id: 5, parent_id: 2, name: 'C2.1' },
    _changed: {},
    _modelOptions: 
     { timestamps: true,
       validate: {},
       freezeTableName: false,
       underscored: true,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: [Object],
       indexes: [],
       name: [Object],
       omitNull: false,
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    _options: 
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       raw: true,
       attributes: [Array] },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false },
  Category {
    dataValues: { id: 6, parent_id: 3, name: 'C3.1' },
    _previousDataValues: { id: 6, parent_id: 3, name: 'C3.1' },
    _changed: {},
    _modelOptions: 
     { timestamps: true,
       validate: {},
       freezeTableName: false,
       underscored: true,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: [Object],
       indexes: [],
       name: [Object],
       omitNull: false,
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    _options: 
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       raw: true,
       attributes: [Array] },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false } ]
```

**Comment by overlookmotel** [comment] 2017-08-09 22:19
Hi @aaronovz1.

Ah OK, I had misunderstood. Can you tell me what version of sequelize and sequelize-hierarchy you are using?

And also (sorry that this is probably a silly question) but can you please check that you spelled `hierarchy` correctly in `.findAll({hierarchy: true})`. I only ask because your original post said `findAll({hiararchy: true})`. Obviously, if it's spelled wrong it won't work.

Also, what result do you get if you miss out the `attributes` option? Please can you post the output?

It seems really odd that you're having this problem, as an example very similar to yours is covered in the tests.

**Comment by aaronovz1** [comment] 2017-08-09 22:28
I am using the latest release of both which is 4.4.2 (I also tried 4.0.0) and 1.3.1 for sequelize-hierarchy. The spelling is correct I just messed it up in the text part of the first comment, you'll see it is correct in all the code snippets (and I triple checked in my code too :) ). Here is the output without the attributes option:

```
[ Category {
    dataValues: 
     { id: 1,
       name: 'C1.0',
       created_at: 2017-08-04T22:23:26.000Z,
       updated_at: 2017-08-04T22:23:26.000Z,
       hierarchy_level: 1,
       parent_id: null },
    _previousDataValues: 
     { id: 1,
       name: 'C1.0',
       created_at: 2017-08-04T22:23:26.000Z,
       updated_at: 2017-08-04T22:23:26.000Z,
       hierarchy_level: 1,
       parent_id: null },
    _changed: {},
    _modelOptions: 
     { timestamps: true,
       validate: {},
       freezeTableName: false,
       underscored: true,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: [Object],
       indexes: [],
       name: [Object],
       omitNull: false,
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    _options: 
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       raw: true,
       attributes: [Array] },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false },
  Category {
    dataValues: 
     { id: 2,
       name: 'C2.0',
       created_at: 2017-08-04T22:23:26.000Z,
       updated_at: 2017-08-04T22:23:26.000Z,
       hierarchy_level: 1,
       parent_id: null },
    _previousDataValues: 
     { id: 2,
       name: 'C2.0',
       created_at: 2017-08-04T22:23:26.000Z,
       updated_at: 2017-08-04T22:23:26.000Z,
       hierarchy_level: 1,
       parent_id: null },
    _changed: {},
    _modelOptions: 
     { timestamps: true,
       validate: {},
       freezeTableName: false,
       underscored: true,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: [Object],
       indexes: [],
       name: [Object],
       omitNull: false,
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    _options: 
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       raw: true,
       attributes: [Array] },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false },
  Category {
    dataValues: 
     { id: 3,
       name: 'C3.0',
       created_at: 2017-08-04T22:23:26.000Z,
       updated_at: 2017-08-04T22:23:26.000Z,
       hierarchy_level: 1,
       parent_id: null },
    _previousDataValues: 
     { id: 3,
       name: 'C3.0',
       created_at: 2017-08-04T22:23:26.000Z,
       updated_at: 2017-08-04T22:23:26.000Z,
       hierarchy_level: 1,
       parent_id: null },
    _changed: {},
    _modelOptions: 
     { timestamps: true,
       validate: {},
       freezeTableName: false,
       underscored: true,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: [Object],
       indexes: [],
       name: [Object],
       omitNull: false,
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    _options: 
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       raw: true,
       attributes: [Array] },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false },
  Category {
    dataValues: 
     { id: 4,
       name: 'C1.1',
       created_at: 2017-08-04T22:23:26.000Z,
       updated_at: 2017-08-04T22:23:26.000Z,
       hierarchy_level: 2,
       parent_id: 1 },
    _previousDataValues: 
     { id: 4,
       name: 'C1.1',
       created_at: 2017-08-04T22:23:26.000Z,
       updated_at: 2017-08-04T22:23:26.000Z,
       hierarchy_level: 2,
       parent_id: 1 },
    _changed: {},
    _modelOptions: 
     { timestamps: true,
       validate: {},
       freezeTableName: false,
       underscored: true,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: [Object],
       indexes: [],
       name: [Object],
       omitNull: false,
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    _options: 
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       raw: true,
       attributes: [Array] },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false },
  Category {
    dataValues: 
     { id: 5,
       name: 'C2.1',
       created_at: 2017-08-04T22:23:26.000Z,
       updated_at: 2017-08-04T22:23:26.000Z,
       hierarchy_level: 2,
       parent_id: 2 },
    _previousDataValues: 
     { id: 5,
       name: 'C2.1',
       created_at: 2017-08-04T22:23:26.000Z,
       updated_at: 2017-08-04T22:23:26.000Z,
       hierarchy_level: 2,
       parent_id: 2 },
    _changed: {},
    _modelOptions: 
     { timestamps: true,
       validate: {},
       freezeTableName: false,
       underscored: true,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: [Object],
       indexes: [],
       name: [Object],
       omitNull: false,
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    _options: 
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       raw: true,
       attributes: [Array] },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false },
  Category {
    dataValues: 
     { id: 6,
       name: 'C3.1',
       created_at: 2017-08-04T22:23:26.000Z,
       updated_at: 2017-08-04T22:23:26.000Z,
       hierarchy_level: 2,
       parent_id: 3 },
    _previousDataValues: 
     { id: 6,
       name: 'C3.1',
       created_at: 2017-08-04T22:23:26.000Z,
       updated_at: 2017-08-04T22:23:26.000Z,
       hierarchy_level: 2,
       parent_id: 3 },
    _changed: {},
    _modelOptions: 
     { timestamps: true,
       validate: {},
       freezeTableName: false,
       underscored: true,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: [Object],
       indexes: [],
       name: [Object],
       omitNull: false,
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    _options: 
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       raw: true,
       attributes: [Array] },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false } ]
```

**Comment by aaronovz1** [comment] 2017-08-15 17:32
Were you able to reproduce the issue?

**Comment by overlookmotel** [comment] 2017-08-29 15:41
Hi @aaronovz1.

No, I can't reproduce it. I've created a branch with a test case which matches yours: https://github.com/overlookmotel/sequelize-hierarchy/tree/issue-133

Tests are running on Travis CI now (https://travis-ci.org/overlookmotel/sequelize-hierarchy/builds/269645080) but passes fine on my laptop.

Can you look at the test case and figure our how it differs from your non-working example?

**Comment by aaronovz1** [comment] 2017-09-13 00:14
I can't see where the difference is. Is this perhaps a problem with the version of Node or MySQL? I am running Node 8.5.0 and MySQL 5.7.19.

What I see when I use the creation and logging code from your test:

```
Executing (default): SELECT `id`, `parent_id`, `name` FROM `Categories` AS `Category`;
categories: [ { name: 'a' },
  { name: 'ac' },
  { name: 'ab' },
  { name: 'abe' },
  { name: 'abd' },
  { name: 'abdg' },
  { name: 'abdf' } ]
```

**Comment by Czystyl** [comment] 2017-09-13 17:43
I have the same issues with `.findAll({hierarchy: true})` 

node: v8.5.0
sequelize: 4.8.3
sequelize-hierarchy: 1.3.1

**Comment by Czystyl** [comment] 2017-09-19 12:28
@aaronovz1 
I found why my `.findAll({ hierarchy: true })` do not work. 

Loading ```hierarchy(sequelize);``` need to be place before creating `Sequelize` instance.

**Comment by aaronovz1** [comment] 2017-09-19 16:10
@Czystyl can you elaborate on your last statement? I am not sure what you mean. Can you provide a real code example? Thanks

**Comment by Czystyl** [comment] 2017-09-19 16:30
```
import Sequelize from 'sequelize';
import hierarchy from 'sequelize-hierarchy';

test('test heirarchy', () => {
  hierarchy(Sequelize);

  const SequelizeInstance = new Sequelize('test', 'root', '123', { dialect: 'mysql' } );

  // working correctly 

```
You need load `hierarchy` before create sequelize instance.

If you load `hierarchy(sequelize);` after creating sequelize instancje then it's not working correctly   
```
const SequelizeInstance = new Sequelize('test', 'root', '123', { dialect: 'mysql' } );

Hierarchy(Sequelize);

// bad way
```

**Comment by aaronovz1** [comment] 2017-09-19 16:37
Ah! Yes that resolved my issue too. Nice work thank you!

**Comment by overlookmotel** [comment] 2017-09-19 18:34
Ah right. I never thought of that! Does that mean this issue can be closed?

**Comment by Czystyl** [comment] 2017-09-19 18:45
:+1:

**Comment by aaronovz1** [comment] 2017-09-19 19:02
I believe it can be. Might be worth noting somewhere in the documentation though?

**Comment by overlookmotel** [comment] 2017-09-20 12:26
Well the docs already show the correct order so I think that's unnecessary.

**Closed** 2017-09-20 12:26 UTC
Labels: possible bug

**Comment by ekeuus** [comment] 2018-10-08 19:35
Does this also work with cases, where the hierarchy is inside an include?

`Models.Parent.findAll({
		include: [
			{
				model: Models.Child,
				hierarchy: true,
                          }
                 ],
});`

**Comment by overlookmotel** [comment] 2018-10-08 23:43
@ekeuus Yes it should. If it doesn't, please open a separate issue - your question doesn't have anything to do with this issue.
