### ISSUE TITLE
alot of keyconstraints with simple example that eventually worked.

### ISSUE THREAD

**Issue by DenLilleMand** [overlookmotel/sequelize-hierarchy#22] opened 2015-09-03 13:46 UTC
Hey so ive provided a gist: https://gist.github.com/DenLilleMand/30e81f50bffa8235d8c4

I dont think this gist looks anything like the official docs, regarding the fact that i had 
to call sync on the folderAncestor model.  

sometimes it works, and sometimes it doesn't, i think i have a race-condition somewhere,
but i cannot see it for the love of god, and since im completely new to your library im not entirely sure how to debug :)

the gist should be able to be runned with just  node <scriptname> having a db connection ofc.

**Comment by overlookmotel** [comment] 2015-09-09 11:45
Hi @DenLilleMand.

I'll look into this. In the meantime, can you tell me in what sense does it sometimes not work? An error is thrown, or it hangs, or the data in the database ends up wrong?

**Comment by overlookmotel** [comment] 2016-06-25 15:00
@DenLilleMand Finally looked into this.

I think the problem is the order in which you are syncing the tables. `folderAncestor` model has relationships to `folder` model. So you can't sync the `folderAncestor` model before the `folder` model is synced - otherwise `folderAncestor` is trying to reference a table that don't exist yet.

On the other hand, if you already have `folder` table created with data in it, then you can't drop that table (which is the first thing `model.sync( { force: true } )` does) while `folderAncestor` table exists - because `folderAncestor` references `folder` table.

Replace `Promise.all( [ drive.sync( {force:true} ), folderAncestor.sync( {force:true} ), folder.sync( {force:true} ) ] )` with `sequelize.sync( {force: true} )` and your example works fine.

I don't think this is a bug in `sequelize-hierarchy` so closing this issue.

**Closed** 2016-06-25 15:01 UTC
